Add support for select * and select table.*
metabase/macaw pull request #13
Opened 2024-03-18 17:22 UTC by tsmacdonald

Fixes the Macaw side of https://github.com/metabase/metabase/issues/40247

A bonus is that this opens the door wide open for saying what table a column comes from (since we can resolve aliases now).

I tried to make the code as self-documenting as possible. The basic ideas are:

1. JParseSQL gives us access to `select *` and `select table_or_alias.*` things via the `AllColumns` and `AllTableColumns` classes.
2. It's easy to extend our existing patterns to capture those while doing the visit.
3. To handle table-stars correctly we need to resolve aliases, so now we maintain a map of them.

Arguably core.clj is getting crowded, but I'm waiting for it to get a little more complex before breaking out into another ns.

2024-03-18 17:29 UTC, tsmacdonald commented on java/com/metabase/macaw/AstWalker.java
> +        // you need to visit the `orders` in `orders.id`. That table is distinct from the one in `from orders`.
@crisptrutski this was a fun one to figure out :sweat_smile: (we were pairing when it seemed like a good idea to remove this. In fairness, it _did_ seem like a good idea!)

2024-03-18 17:29 UTC, tsmacdonald commented on java/com/metabase/macaw/AstWalker.java
> +        invokeCallback(ALL_TABLE_COLUMNS, allTableColumns);
This isn't called in 4.8 (that's the bug), but we're leaving it as a future-proofing.

2024-03-18 17:30 UTC, tsmacdonald commented on src/macaw/core.clj
> +  (fn item-conjer [results item]
added the fn name to make stack traces clearer :shrug:

2024-03-18 19:14 UTC, crisptrutski requested changes

2024-03-19 09:04 UTC, tsmacdonald commented on java/com/metabase/macaw/AstWalker.java
> +        // you need to visit the `orders` in `orders.id`. That table is distinct from the one in `from orders`.
afaik that would require machinations like this in `rewrite.clj` though:

```
  (-> parsed-ast
      (mw/walk-query
       {:table  (fn [^Table table] (when-let [name' (get table-renames (.getName table))]
                                     (.setName table name')))
        :column-table  (fn [^Table table] (when-let [name' (get table-renames (.getName table))]
                                            (when-not (alias? (.getName table))
                                              (.setName table name'))))
```        

or maybe something slightly-cleverer to handle aliases. Now that I think about it, I'm pretty sure alias rewriting is broken as-is. but the general point remains that it feels irresponsible to make the rewrite walker provide two callbacks that do nearly the same thing

2024-03-19 09:05 UTC, tsmacdonald commented on java/com/metabase/macaw/AstWalker.java
> +        invokeCallback(ALL_TABLE_COLUMNS, allTableColumns);
I was going to say "4.9 being released", but it came out last week! Will upgrade in a separate PR.

2024-03-19 09:06 UTC, tsmacdonald commented on java/com/metabase/macaw/AstWalker.java
> +     * should be a (Clojure) map of CallbackKeys to reducing functions.
Sorry, I'm also aligned on 120, I just need to keep reminding Vim that this is how it is.

2024-03-19 09:07 UTC, tsmacdonald commented on src/macaw/core.clj
> +                                (update results :select-star? (constantly true)))
this was one of those "there's something really obvious that I'm just blanking on" moments. I couldn't get `swap` (without the bang) out of my head, which of course doesn't exist.

2024-03-19 12:04 UTC, piranha commented on test/macaw/core_test.clj
> +(deftest ^:parallel table-star-test-with-aliases
With metadata you can have some tests which can run in parallel and some which cannot? Also you can put `^:parallel` on a namespace.

2024-03-19 12:27 UTC, crisptrutski commented on test/macaw/core_test.clj
> +(deftest ^:parallel table-star-test-with-aliases
TIL re: putting it on a namespace. That's much nicer than doing weird stuff with aliases, which actually affected my sleep when I realized what a bad idea it was 😆

2024-03-19 17:01 UTC, tsmacdonald commented on src/macaw/core.clj
> +  (fn item-conjer [results item]
I don't see a meaningful distinction between `conj-to` and `conj-into`.

I think that since it's a private function that appears directly next to where it's used I'm not going to lose lots of sleep over it. As long as all this easily fits into an eyeful I think it's fine.

![image](https://github.com/metabase/macaw/assets/784417/47d042b4-b2d8-4339-bd34-ed4976418e47)

2024-03-19 17:03 UTC, crisptrutski commented on src/macaw/core.clj
> +  (fn item-conjer [results item]
Haha, line-of-sight as visibility criteria. Imagine enforcing that with metadata and a linter 😆

2024-03-19 17:07 UTC, tsmacdonald commented on src/macaw/core.clj
> +     :tables       (into #{} (remove-aliases aliases (map #(.getName ^Table %) tables)))
:grimacing: 

https://github.com/metabase/macaw/issues/14

Added to [the roadmap](https://github.com/metabase/metabase/issues/36911)

![image](https://github.com/metabase/macaw/assets/784417/547eb2a9-f05e-4147-a4d4-269a967d9267)

2024-03-19 17:14 UTC, tsmacdonald commented on java/com/metabase/macaw/AstWalker.java
> +     * should be a (Clojure) map of CallbackKeys to reducing functions.
:heavy_check_mark: 
![image](https://github.com/metabase/macaw/assets/784417/b3ebeb98-c5b0-49ef-a9f0-1c3ad0a6498a)

2024-03-19 17:19 UTC, tsmacdonald commented
@crisptrutski thanks for the thoughtful comments, as always. Fixed the refactors I agreed with, gently pushed back on the ones I didn't care about, and filed #14 for the actually-pretty-serious alias bug that I don't think should be fixed in this PR. Like we said…somewhere…(Slack?) it'll be much easier to tackle once we're tracking which part of a query a table ref appears in.

Got seriously nerdsniped trying to extend the Kondo hook to work with ns-level `^:parallel` declarations and then decided that it was impossible. Sigh.

2024-03-19 17:23 UTC, crisptrutski approved these changes
Feel a bit weird about punting the alias shadowing issue. While it's a real fringe case, and we've got good tracking on it, I feel such a sense of dread for the knock-on impact for processes using this data.

We don't have a lot of that use yet, and our parser is certain to have all sorts of rough edges for a while though, so I think this is just a feeling I need to get used to.

2024-03-21 08:44 UTC, merged