Implement query->columns using the new SqlVisitor interface
metabase/macaw pull request #3
Opened 2024-02-15 11:09 UTC by tsmacdonald

The best introduction to this is the javadoc for `SqlVisitor.java`. I'll also add comments to key places in the source code.

2024-02-15 11:11 UTC, tsmacdonald commented on build.clj
> +      "9999-SNAPSHOT"))
Shoutout to Cam for writing this in `second-date`

2024-02-15 11:11 UTC, tsmacdonald commented on java/com/metabase/SqlVisitor.java
> + */
Read this first!

2024-02-15 11:12 UTC, tsmacdonald commented on java/com/metabase/macaw/ASTWalker.java
> +        this.sqlVisitor.visitTable(table);
This (and similar for columns) is one of the key changes from `TablesNamesFinder.java`, which this is mostly a copy-and-paste of. The original class kept a `List` of table names that were added to in this method.

2024-02-15 11:13 UTC, tsmacdonald commented on java/com/metabase/macaw/ASTWalker.java
> +        this.sqlVisitor.visitTable(table);
"Tim, why did you copy TNF.java?"

Because walking the AST is a lot of legwork and TNF already implemented it nicely.

2024-02-15 11:16 UTC, tsmacdonald commented on src/macaw/core.clj
> +    @column-names))
while lying in bed this morning I started to fantasize about adding some sort of context+results object as an argument to the visit____ methods so that 1) we didn't have to close over the `columns` atom 2) we could keep the breadcrumbs of what part of a SQL query the column/table was found in.

That's likely to happen at some point. But for now this way works and I don't want to make things too complicated too early.

2024-02-15 11:17 UTC, tsmacdonald commented on test/macaw/core_test.clj
> +           (columns "select foo, bar from baz inner join quux on quux.id = baz.quux_id")))))
It's part of the tech plan to source crazy queries to parse, but for now I just have the one as a sanity check. JSqlParser is doing all the heavy lifting, so this test exists to make sure that we're using JSqlParser correctly. On a separate occasion, we'll do testing to find the holes in JSqlParser's coverage.

2024-02-15 11:48 UTC, crisptrutski commented on build.clj
> +      "9999-SNAPSHOT"))
Very cute that you took it out for a second date on Valentine's day. Whoops, "took it out *from* second date"

2024-02-15 11:51 UTC, crisptrutski commented on java/com/metabase/SqlVisitor.java
> + * definition has been lost.
Perhaps I'm misreading this, but here's an explanation of my understanding:

The call to proxy-super calls down to a proxy instance of `TableNamesFinder`, and its recursive calls to `visit` do not reach back up to our proxy's overriden version.

2024-02-15 11:56 UTC, crisptrutski commented on src/macaw/core.clj
> +    @column-names))
That I like that idea, basically doing a fold over the tree, creeping towards catamorphism 👽

2024-02-15 11:59 UTC, crisptrutski commented on src/macaw/core.clj
> +    (.walk (ASTWalker. column-finder) parsed-query)
Not sure about this interface, I was thinking of having something like:

```clojure
(query/walk 
  {:column (fn [^Column column] (swap! column-names conj (.getColumnName column))}
  parsed-query)
```

2024-02-15 12:03 UTC, crisptrutski commented on src/macaw/core.clj
> +    (.walk (ASTWalker. column-finder) parsed-query)
Given we're going to do accumulate things pretty often, perhaps even have some sugar over that:

```clojure
(query/gather
  {:column #(.getColumnName ^Column %)}
  parsed-query)
```

That could return a map of keys to all the non-nil values calculated from the corresponding node visits.

2024-02-15 12:04 UTC, crisptrutski commented on java/com/metabase/macaw/ASTWalker.java
> +import net.sf.jsqlparser.expression.operators.relational.ExistsExpression;
Maybe some `.*` imports are OK in this case 😅

2024-02-15 12:08 UTC, crisptrutski commented on java/com/metabase/macaw/ASTWalker.java
> +        this.sqlVisitor.visitTable(table);
Rather than a comments in Github, you could defend the design (and guide future maintainers) with comments.

1. Have a "This class copies TNF as of <link to revision>. {{reasons}}. See method docstrings for where we have deviated"
2. Docstrings to mark the surgical spots where you changed stuff.

2024-02-15 12:14 UTC, crisptrutski commented on java/com/metabase/SqlVisitor.java
> +}
This is not the kind of interface I imagined. I'd prefer to get away from needing to extend or implement anything.

The idea I had was for there to a concrete class, your "copy" of TNF, with the major difference being that it takes a `Map<String, Consumer<Visitable>>` argument in its constructor. 

For each overloading of visit, it would check if the given map has an entry for the corresponding type, and if so call it with its argument before calling the rest of its own traversal code.

2024-02-15 12:32 UTC, tsmacdonald commented on java/com/metabase/SqlVisitor.java
> +}
That's my bad for misunderstanding.

I was going to start bikeshedding about whether this was all a moot point after the context/results object was added above, but on further reflection I think that's orthogonal.

I think the two approaches are maybe not so different? Here are the pros (in bold) and cons I can see:

| `SqlVisitor` interface | Map of fns |
|-|-|
| **Type safety: can't forget or mis-type a `visit___` method**  | (was it `:columns` or `:column`?) | 
| **Avoids the faff of making a helper to turn `fn`s into a `Consumer` instance.** Although I suppose we could use `IFn` directly | |
| verbose for the client code | **More Clojure-y interface; using `reify` is kind of a pain; avoids providing blank implementations for unneeded methods**
| | **The `gather` sugar is nice** |

I don't think there's a slam-dunk argument in either direction, so my bias is to leave it for now and use a) accumulating other things (we've done it…once!) or b) needing the query context as the opportunity to refactor as wanted?

2024-02-15 12:41 UTC, crisptrutski commented on java/com/metabase/SqlVisitor.java
> +}
Thanks for making the table, here are my thoughts:

1. "Can't forget a visit method" - the list we support may get quite long, painful to be exhaustive.
2. "Was it :columns or :column" - spec / malli / kondo / assert to the rescue
3. "Avoids the faff of turning fns to Consumer" - whoops, I thought Clojure magically made this work now. This is a Clojure oriented library so we could definitely use `IFn` in the map, and maybe even `Keyword` too, but I think converting to String before passing to the constructor will be more ergonomic.

For me the key thing is how pleasant this is to work with as we start to care about more kinds of leaves and clauses. I'm OK to go with what works and rework as we add more requirements. 

Will give this a closer look tomorrow, just did a high level flyby. Also interested to hear others opinions before I commit to a tick 😄

2024-02-15 12:50 UTC, crisptrutski commented on java/com/metabase/SqlVisitor.java
> +}
Something like this looks quite nice to me

```clojure
(defn- kv->java [[k f]]
  [(name k)
   (reify java.util.function.Consumer
     (accept [_this item]
       (f item)))])

;; Malli stuff on the args
(defn walk-query [visitor-map parsed-query]
  (.run (MyFancyVisitor. (into {} (map kv->java) visitor-map)
           parsed-query)
```

2024-02-15 13:02 UTC, crisptrutski commented on java/com/metabase/SqlVisitor.java
> +}
Ah, just thought of a few more potential benefits to the "data oriented" approach:

1. Fusion - we can do things like `(merge-with call-both)` over all our walkers, and do a single walk for efficiency.
2. Decoration - easy to wrap functions, e.g. for debugging or logging.
3. Derivation - maybe we can derive more complete mappings from incomplete maps.
4. Generalization - perhaps nice register functions for some group of entities in a hierarchy

I just love data, man 🌈

2024-02-15 14:26 UTC, tsmacdonald commented on java/com/metabase/SqlVisitor.java
> +}
Cool, I'm persuaded!

2024-02-15 15:17 UTC, piranha commented on java/com/metabase/SqlVisitor.java
> +}
> "Avoids the faff of turning fns to Consumer" - whoops, I thought Clojure magically made this work now. This is a Clojure oriented library so we could definitely use IFn in the map, and maybe even Keyword too, but I think converting to String before passing to the constructor will be more ergonomic.

Clojure 1.12 will!

2024-02-15 17:23 UTC, crisptrutski commented on java/com/metabase/SqlVisitor.java
> +}
I thought I'd heard something! The design and how they reached it is really interesting https://clojure.atlassian.net/browse/CLJ-2799. 

Unfortunately it won't cover the case of pulling an IFn out of the map in Java, no automatic conversion there. It would make `kv->java` a one liner though, and lambda conversions look so nice and light compared to reify 😍

2024-02-19 17:09 UTC, tsmacdonald commented on java/com/metabase/macaw/ASTWalker.java
> +import net.sf.jsqlparser.expression.operators.relational.ExistsExpression;
I'm not opposed to `.*`s in the future, but it felt bad to remove the carefully-selected imports and drop a bunch of stars in there.

2024-02-19 17:10 UTC, tsmacdonald commented on java/com/metabase/SqlVisitor.java
> +}
Updated! There's some Clojure lib-specific voodoo on the Java side, but that doesn't matter.

2024-02-19 17:18 UTC, tsmacdonald commented on java/com/metabase/SqlVisitor.java
> +}
The implementation is very much about making the Clojure code look as clean as possible, to the detriment of cute Java.

2024-02-19 17:20 UTC, tsmacdonald commented on src/macaw/core.clj
> +    (.walk (ASTWalker. column-finder) parsed-query)
Not strictly opposed to the sugar, but I'm not mad enough about the desugared approach to change it yet.

2024-02-19 17:20 UTC, tsmacdonald commented on src/macaw/core.clj
> +    (.walk (ASTWalker. column-finder) parsed-query)
trying to walk the fine line between "sugar" and "unnecessary abstraction"

2024-02-20 08:53 UTC, tsmacdonald commented on java/com/metabase/SqlVisitor.java
> +}
> "Was it :columns or :column" - spec / malli / kondo / assert to the rescue

Malli is on the radar, but…not in this PR ;)

2024-02-20 09:18 UTC, qnkhuat commented on src/macaw/core.clj
> +  (let [column-names (atom #{})
```suggestion
  (let [column-names (transient #{})
```
does `.walk` multi-threaded? if not we can use transient for a bit of a performance boost

2024-02-20 10:05 UTC, tsmacdonald commented on src/macaw/core.clj
> +  (let [column-names (atom #{})
Good call, changed!

Arguments could be made for parallelizing `walk`, but that's non-zero effort and I'm afraid will backfire on us if/when we get around to mutating column and table names.

2024-02-20 10:14 UTC, crisptrutski commented on java/com/metabase/macaw/ASTWalker.java
> +import net.sf.jsqlparser.expression.operators.relational.ExistsExpression;
I let IntelliJ manage my imports, and it can toggle between stars and explicit by changing a setting. I don't mind much either way, but in this case I don't think the namespace each class comes from is important semantically, and we could save some noise in future PRs. If you're just mirroring the imports from TNF fair enough.

2024-02-20 10:38 UTC, tsmacdonald commented on java/com/metabase/macaw/ASTWalker.java
> +import net.sf.jsqlparser.expression.operators.relational.ExistsExpression;
Yeah, I copied the initial set from TNF then let my in-editor very basic linter tell me which ones were no longer used :shrug:

2024-02-20 10:41 UTC, crisptrutski requested changes
My only blocking comments are around NPEs and a subtle bug with using transients, but here take this nits as well 😄

2024-02-20 10:41 UTC, crisptrutski commented on README.md
> +2. Restart your Clojure REPL
Is there no way to improve this workflow in 2024? 😢 (outside scope of this PR)

2024-02-20 10:41 UTC, crisptrutski commented on java/com/metabase/macaw/ASTWalker.java
> + * Walks the AST, using JSqlParser's `visit()` methods. Each `visit()` method additionally calls an applicable callback method provided in the `callbacks` map.
nitpick: Inconsistent line width

2024-02-20 10:41 UTC, crisptrutski commented on java/com/metabase/macaw/ASTWalker.java
> +        this.callbacks = new HashMap<String, IFn>(SUPPORTED_CALLBACK_KEYS.length);
Comment: One thing I really like about doing the key transformation in here is that we encapsulate a copy of the argument, rather than assuming it's already immutable - which Java's types can't enforce.

Note: that this constructor might not be allocating enough capacity, as it is not considering the load factor. You should instead be using `HashMap.newHashMap`, if you're on Java 19 or later.

Idea: it might be worth asserting that there are no unknown callback keys in this map, particularly since we don't have Malli or friends providing validation in the Clojure wrapper (yet).

2024-02-20 10:41 UTC, crisptrutski commented on java/com/metabase/macaw/ASTWalker.java
> +            this.callbacks.put(entry.getKey().getName(), entry.getValue());
This will register functions even if they're not for known callbacks, it may make more sense to loop over the known keys instead. This would also give us the opportunity to register "no-op" functions and simplify where we call the callbacks.

The stickler in me would also prefer if we worked with `Consumer` rather than `IFn`, but it's probably not worth doing this until the next Clojure release makes that conversion cheaper.

2024-02-20 10:41 UTC, crisptrutski commented on java/com/metabase/macaw/ASTWalker.java
> +        this.callbacks.get(TABLE_STR).invoke(table);
I think this can NPE currently, but see my previous comment for one way to get around this. Other options would be to use `containsKey` or `getOrDefault` with a `NOOP` Ifn.

2024-02-20 10:41 UTC, crisptrutski commented on src/macaw/core.clj
> +  (Specifically, it returns their fully-qualified names as strings, where 'fully-qualified' means 'as found in the query'.)"
Maybe it's worth being super explicit and saying something like "where names are not qualified within the query, they are returned as simple names, without the namespace (table) being inferred."

2024-02-20 10:41 UTC, crisptrutski commented on src/macaw/core.clj
> +  (Specifically, it returns their fully-qualified names as strings, where 'fully-qualified' means 'as found in the query'.)"
To handle the general case in future I guess the parser will need to do this inference if we want it, as it may depend on the scope in a nested query. No need to say anything about that, just musing.

2024-02-20 10:41 UTC, crisptrutski commented on src/macaw/core.clj
> +                                          (conj! column-names (.getColumnName column)))
Unfortunately you can't replace an atom with a transient like this:

> Note in particular that transients are not designed to be bashed in-place. You must capture and use the return value in the next call. 

(Taken from https://clojure.org/reference/transients)

The current code can break if the underlying tree ends up inserting a root above the node being referenced, so it's an evil case where it can still work for small examples.

You could wrap the transient in a volatile, but I also think an atom is fine.

2024-02-20 11:35 UTC, qnkhuat commented
not blocking but I'd like your thoughts on this approach
```clojure
(require '[methodica.core :as m])
(import (net.sf.jsqlparser.parser
         CCJSqlParserUtil)
        (net.sf.jsqlparser.schema
         Column
         Table)
        (net.sf.jsqlparser.statement.select
         Select
         SelectItem
         PlainSelect))


(m/defmulti ast-walker
  (fn [obj _collector]
    (class obj)))

(m/defmethod ast-walker :default
  [_obj _collector]
  nil)

(m/defmethod ast-walker :around :default
  [obj collector]
  (collector obj)
  (next-method obj collector))

(m/defmethod ast-walker Select
  [obj collector]
  (when (some? (.getSelectItems obj))
    (run! #(ast-walker % collector) (.getSelectItems obj)))
  (when
    (some? (.getFromItem obj))
    (ast-walker (.getFromItem obj) collector)))

(m/defmethod ast-walker SelectItem
  [obj collector]
  (ast-walker (.getExpression obj) collector))

(defn get-table-and-columns
  [query]
  (let [data         (atom {:columns []
                            :tables  []})
        collector    (fn [x]
                       (cond-> data
                         (instance? Table x)
                         (swap! update :tables conj (.getName x))

                         (instance? Column x)
                         (swap! update :columns conj (.getFullyQualifiedName x true))))]
    (ast-walker (CCJSqlParserUtil/parse query) collector)
    @data))

(get-table-and-columns "select id, name from my_table")

;; => {:columns ["id" "name"], :tables ["my_table"]}
```
this is an "improvised" visitor pattern in Clojure :D, where all the primary implementation just walk the query. 
The real side-affect is done in the around method (read more about it [here](https://github.com/camsaul/methodical?tab=readme-ov-file#around-methods))

```clojure
(m/defmethod ast-walker :around :default
  [obj collector]
  (collector obj)
  (next-method obj collector))
```

this ensures `collector` will be called on all objects that `ast-walker` walks through.

I think the only cons here is that we have to implement the walking logic, but that's doable, especially we have the TNF class as a reference.

would love to have your thoughts on this :)

2024-02-20 13:45 UTC, tsmacdonald commented on README.md
> +2. Restart your Clojure REPL
possibly with the right ns refresh, but I haven't worked it out :(

2024-02-20 15:31 UTC, tsmacdonald commented
@qnkhuat that's effectively what we have in Java (just without elegant Clojure/methodical sugar); the problem is that there are so many classes to deal with. I haven't run your code, but I don't see how it could deal with joins, for example. At some point you'd end up with about 1000 lines of Clojure that were very similar to the current ASTWalker class.

An argument could be made for…doing just that. Translating the code would be tedious but ultimately not take _that_ long. I didn't because I had a preference for adapting a well-tested, library-endorsed Java file rather than DIYing it, and with all the scar tissue I have from Clojure-Java interop I strongly suspect that future concerns will be glad to have the Java escape hatch. For example, getting the line/column information out of the parse tree looks like it's going to be a mess and almost certainly easier on the Java side.

2024-02-20 16:51 UTC, crisptrutski commented
On the topic of multimethods, your example looks a lot like an early prototype Tim show me. Semantically it's still very close to this Java based solution, and here are my thoughts on the relative merits.

Java pros:

1. Java tooling is very good at generating and editing boilerplate, because its intrinsic.
2. We can easily copy-paste from upstream if AST changes, without needing to reconvert.
3. Faster - not using dynamic dispatch, and avoiding reflection.

None of these are game changers, but they add up.

Multi-methods pros:

1. Avoid mixing languages and an inferior REPL workflow.
2. Powerful meta programming tools, like :around and multiple dispatch, but do we need them?
3. ... not sure what I'm missing?

In my opinion the benefits here are less clear, and I think it will overall be more painful to work with. This is the crux of my preference for "just java".

2024-02-20 16:52 UTC, crisptrutski commented on java/com/metabase/macaw/ASTWalker.java
> +    public static final Set<String> SUPPORTED_CALLBACK_KEYS = Set.of(COLUMN_STR, TABLE_STR);
Let's leave this for another day, but I realized that using an Enum for these values would also let you use an `EnumMap` for `callbacks`, which is much more efficient that a regular map.

2024-02-20 16:53 UTC, crisptrutski approved these changes
LGTM

2024-02-20 16:58 UTC, merged

2024-02-21 05:51 UTC, qnkhuat commented
I guess I just love control from my REPL, and also, by taking a `collector`, we can de-couple logic to get tables and column names from the Java class.

But anyway I think the point about using well-tested code makes sense.